services:
  krazeplanet:
    image: rix4uni/krazeplanet:main
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krazeplanet
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
    environment:
      - TZ=UTC
    volumes:
      - .:/opt/lampp/htdocs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mailpit

  lab-runtime:
    image: rix4uni/krazeplanet:lab-runtime
    build:
      context: .
      dockerfile: Dockerfile.lab_runtime
    restart: "no"
    entrypoint: ["echo", "Lab runtime image built successfully"]

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MP_MAX_MESSAGES=10000
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
