<?php
$db_file = __DIR__ . '/upchieve.db';
if (file_exists($db_file)) { @chmod($db_file, 0666); }
@chmod(__DIR__, 0777);
$pdo = new PDO('sqlite:' . $db_file);
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$pdo->setAttribute(PDO::ATTR_TIMEOUT, 30);
$pdo->exec("PRAGMA journal_mode=WAL;");
$pdo->exec("PRAGMA busy_timeout=30000;");
$pdo->exec("PRAGMA synchronous=NORMAL;");

$pdo->exec("CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE,
    fullname TEXT,
    email TEXT UNIQUE,
    password TEXT,
    role TEXT DEFAULT 'student',
    reset_otp TEXT,
    reset_otp_expiry DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)");

$count = $pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
if ($count == 0) {
    $default_pass = password_hash('StudentPass2026!', PASSWORD_DEFAULT);

    $sample_users = [
        ['alex.smith', 'Alex Smith', 'alex.smith@upchieve.org', 'volunteer'],
        ['sarah.jenkins', 'Sarah Jenkins', 'sarah.jenkins@gmail.com', 'student'],
        ['david.wilson', 'David Wilson', 'david.wilson@yahoo.com', 'student'],
        ['emily.davis', 'Emily Davis', 'emily.davis@outlook.com', 'volunteer'],
        ['michael.brown', 'Michael Brown', 'michael.brown@school.edu', 'student'],
        ['jessica.taylor', 'Jessica Taylor', 'jessica.taylor@gmail.com', 'student'],
        ['daniel.anderson', 'Daniel Anderson', 'daniel.anderson@upchieve.org', 'volunteer'],
        ['olivia.thomas', 'Olivia Thomas', 'olivia.thomas@icloud.com', 'student'],
        ['james.jackson', 'James Jackson', 'james.jackson@protonmail.com', 'student'],
        ['sophia.white', 'Sophia White', 'sophia.white@yahoo.com', 'volunteer'],
        ['william.harris', 'William Harris', 'william.harris@school.edu', 'student'],
        ['ava.martin', 'Ava Martin', 'ava.martin@gmail.com', 'student'],
        ['benjamin.thompson', 'Benjamin Thompson', 'benjamin.thompson@upchieve.org', 'volunteer'],
        ['mia.garcia', 'Mia Garcia', 'mia.garcia@outlook.com', 'student'],
        ['lucas.martinez', 'Lucas Martinez', 'lucas.martinez@gmail.com', 'student'],
        ['charlotte.robinson', 'Charlotte Robinson', 'charlotte.robinson@yahoo.com', 'volunteer'],
        ['henry.clark', 'Henry Clark', 'henry.clark@school.edu', 'student'],
        ['amelia.rodriguez', 'Amelia Rodriguez', 'amelia.rodriguez@gmail.com', 'student'],
        ['alexander.lewis', 'Alexander Lewis', 'alexander.lewis@upchieve.org', 'volunteer'],
        ['harper.lee', 'Harper Lee', 'harper.lee@icloud.com', 'student'],
        ['ethan.walker', 'Ethan Walker', 'ethan.walker@gmail.com', 'student'],
        ['evelyn.hall', 'Evelyn Hall', 'evelyn.hall@outlook.com', 'volunteer'],
        ['jacob.allen', 'Jacob Allen', 'jacob.allen@school.edu', 'student'],
        ['abigail.young', 'Abigail Young', 'abigail.young@yahoo.com', 'student'],
        ['logan.hernandez', 'Logan Hernandez', 'logan.hernandez@upchieve.org', 'volunteer'],
        ['emily.king', 'Emily King', 'emily.king@gmail.com', 'student'],
        ['jackson.wright', 'Jackson Wright', 'jackson.wright@protonmail.com', 'student'],
        ['elizabeth.lopez', 'Elizabeth Lopez', 'elizabeth.lopez@yahoo.com', 'volunteer'],
        ['sebastian.hill', 'Sebastian Hill', 'sebastian.hill@school.edu', 'student'],
        ['sofia.scott', 'Sofia Scott', 'sofia.scott@gmail.com', 'student'],
        ['jack.green', 'Jack Green', 'jack.green@upchieve.org', 'volunteer'],
        ['avery.adams', 'Avery Adams', 'avery.adams@outlook.com', 'student'],
        ['owen.baker', 'Owen Baker', 'owen.baker@gmail.com', 'student'],
        ['ella.gonzalez', 'Ella Gonzalez', 'ella.gonzalez@yahoo.com', 'volunteer'],
        ['theodore.nelson', 'Theodore Nelson', 'theodore.nelson@school.edu', 'student'],
        ['scarlett.carter', 'Scarlett Carter', 'scarlett.carter@gmail.com', 'student'],
        ['samuel.mitchell', 'Samuel Mitchell', 'samuel.mitchell@upchieve.org', 'volunteer'],
        ['chloe.perez', 'Chloe Perez', 'chloe.perez@icloud.com', 'student'],
        ['joseph.roberts', 'Joseph Roberts', 'joseph.roberts@gmail.com', 'student'],
        ['victoria.turner', 'Victoria Turner', 'victoria.turner@outlook.com', 'volunteer'],
        ['john.phillips', 'John Phillips', 'john.phillips@school.edu', 'student'],
        ['grace.campbell', 'Grace Campbell', 'grace.campbell@yahoo.com', 'student'],
        ['david.parker', 'David Parker', 'david.parker@upchieve.org', 'volunteer'],
        ['zoey.evans', 'Zoey Evans', 'zoey.evans@gmail.com', 'student'],
        ['luke.edwards', 'Luke Edwards', 'luke.edwards@protonmail.com', 'student'],
        ['penelope.collins', 'Penelope Collins', 'penelope.collins@yahoo.com', 'volunteer'],
        ['anthony.stewart', 'Anthony Stewart', 'anthony.stewart@school.edu', 'student'],
        ['riley.sanchez', 'Riley Sanchez', 'riley.sanchez@gmail.com', 'student'],
        ['isaac.morris', 'Isaac Morris', 'isaac.morris@upchieve.org', 'volunteer'],
        ['layla.rogers', 'Layla Rogers', 'layla.rogers@outlook.com', 'student'],
        ['gabriel.reed', 'Gabriel Reed', 'gabriel.reed@gmail.com', 'student'],
        ['nora.cook', 'Nora Cook', 'nora.cook@yahoo.com', 'volunteer'],
        ['julian.morgan', 'Julian Morgan', 'julian.morgan@school.edu', 'student'],
        ['lily.bell', 'Lily Bell', 'lily.bell@gmail.com', 'student'],
        ['mateo.murphy', 'Mateo Murphy', 'mateo.murphy@upchieve.org', 'volunteer'],
        ['eleanor.bailey', 'Eleanor Bailey', 'eleanor.bailey@icloud.com', 'student'],
        ['anthony.rivera', 'Anthony Rivera', 'anthony.rivera@gmail.com', 'student'],
        ['hannah.cooper', 'Hannah Cooper', 'hannah.cooper@outlook.com', 'volunteer'],
        ['jayson.richardson', 'Jayson Richardson', 'jayson.richardson@school.edu', 'student'],
        ['lillian.cox', 'Lillian Cox', 'lillian.cox@yahoo.com', 'student'],
        ['carter.howard', 'Carter Howard', 'carter.howard@upchieve.org', 'volunteer'],
        ['addison.ward', 'Addison Ward', 'addison.ward@gmail.com', 'student'],
        ['jayden.torres', 'Jayden Torres', 'jayden.torres@protonmail.com', 'student'],
        ['aubrey.peterson', 'Aubrey Peterson', 'aubrey.peterson@yahoo.com', 'volunteer'],
        ['john.gray', 'John Gray', 'john.gray@school.edu', 'student'],
        ['ellie.ramirez', 'Ellie Ramirez', 'ellie.ramirez@gmail.com', 'student'],
        ['dylan.james', 'Dylan James', 'dylan.james@upchieve.org', 'volunteer'],
        ['stella.watson', 'Stella Watson', 'stella.watson@outlook.com', 'student'],
        ['grayson.brooks', 'Grayson Brooks', 'grayson.brooks@gmail.com', 'student'],
        ['natalie.kelly', 'Natalie Kelly', 'natalie.kelly@yahoo.com', 'volunteer'],
        ['levi.sanders', 'Levi Sanders', 'levi.sanders@school.edu', 'student'],
        ['leah.price', 'Leah Price', 'leah.price@gmail.com', 'student'],
        ['isaiah.bennett', 'Isaiah Bennett', 'isaiah.bennett@upchieve.org', 'volunteer'],
        ['hazel.wood', 'Hazel Wood', 'hazel.wood@icloud.com', 'student'],
        ['andrew.barnes', 'Andrew Barnes', 'andrew.barnes@gmail.com', 'student'],
        ['violet.ross', 'Violet Ross', 'violet.ross@outlook.com', 'volunteer'],
        ['thomas.henderson', 'Thomas Henderson', 'thomas.henderson@school.edu', 'student'],
        ['aurora.coleman', 'Aurora Coleman', 'aurora.coleman@yahoo.com', 'student'],
        ['joshua.jenkins', 'Joshua Jenkins', 'joshua.jenkins@upchieve.org', 'volunteer'],
        ['savannah.perry', 'Savannah Perry', 'savannah.perry@gmail.com', 'student'],
        ['ezra.powell', 'Ezra Powell', 'ezra.powell@protonmail.com', 'student'],
        ['audrey.long', 'Audrey Long', 'audrey.long@yahoo.com', 'volunteer'],
        ['charles.patterson', 'Charles Patterson', 'charles.patterson@school.edu', 'student'],
        ['brooklyn.hughes', 'Brooklyn Hughes', 'brooklyn.hughes@gmail.com', 'student'],
        ['caleb.flores', 'Caleb Flores', 'caleb.flores@upchieve.org', 'volunteer'],
        ['bella.washington', 'Bella Washington', 'bella.washington@outlook.com', 'student'],
        ['ryan.butler', 'Ryan Butler', 'ryan.butler@gmail.com', 'student'],
        ['claire.simmons', 'Claire Simmons', 'claire.simmons@yahoo.com', 'volunteer'],
        ['adrian.foster', 'Adrian Foster', 'adrian.foster@school.edu', 'student'],
        ['skylar.gonzales', 'Skylar Gonzales', 'skylar.gonzales@gmail.com', 'student'],
        ['miles.bryant', 'Miles Bryant', 'miles.bryant@upchieve.org', 'volunteer'],
        ['lucy.alexander', 'Lucy Alexander', 'lucy.alexander@icloud.com', 'student'],
        ['elias.russell', 'Elias Russell', 'elias.russell@gmail.com', 'student'],
        ['paisley.griffin', 'Paisley Griffin', 'paisley.griffin@outlook.com', 'volunteer'],
        ['nathan.diaz', 'Nathan Diaz', 'nathan.diaz@school.edu', 'student'],
        ['everly.hayes', 'Everly Hayes', 'everly.hayes@yahoo.com', 'student'],
        ['colton.myers', 'Colton Myers', 'colton.myers@upchieve.org', 'volunteer'],
        ['anna.ford', 'Anna Ford', 'anna.ford@gmail.com', 'student'],
        ['cameron.hamilton', 'Cameron Hamilton', 'cameron.hamilton@protonmail.com', 'student'],
        ['caroline.graham', 'Caroline Graham', 'caroline.graham@yahoo.com', 'volunteer'],
        ['landon.sullivan', 'Landon Sullivan', 'landon.sullivan@school.edu', 'student'],
        ['nova.wallace', 'Nova Wallace', 'nova.wallace@gmail.com', 'student'],
        ['hunter.woods', 'Hunter Woods', 'hunter.woods@upchieve.org', 'volunteer'],
        ['genesis.cole', 'Genesis Cole', 'genesis.cole@outlook.com', 'student'],
        ['jonathan.west', 'Jonathan West', 'jonathan.west@gmail.com', 'student'],
        ['emilia.jordan', 'Emilia Jordan', 'emilia.jordan@yahoo.com', 'volunteer'],
        ['connor.owens', 'Connor Owens', 'connor.owens@school.edu', 'student'],
        ['kennedy.reynolds', 'Kennedy Reynolds', 'kennedy.reynolds@gmail.com', 'student'],
        ['aaron.fisher', 'Aaron Fisher', 'aaron.fisher@upchieve.org', 'volunteer'],
        ['maya.ellis', 'Maya Ellis', 'maya.ellis@icloud.com', 'student'],
        ['christian.harrison', 'Christian Harrison', 'christian.harrison@gmail.com', 'student'],
        ['willow.gibson', 'Willow Gibson', 'willow.gibson@outlook.com', 'volunteer'],
        ['eli.mcdonald', 'Eli McDonald', 'eli.mcdonald@school.edu', 'student'],
        ['kinsley.cruz', 'Kinsley Cruz', 'kinsley.cruz@yahoo.com', 'student'],
        ['landon.marshall', 'Landon Marshall', 'landon.marshall@upchieve.org', 'volunteer'],
        ['naomi.ortiz', 'Naomi Ortiz', 'naomi.ortiz@gmail.com', 'student'],
        ['aousho9887', 'Aousho Researcher', 'aousho9887@gmail.com', 'volunteer']
    ];

    $stmt_ins = $pdo->prepare("INSERT INTO users (username, fullname, email, password, role) VALUES (?, ?, ?, ?, ?)");
    foreach ($sample_users as $u) {
        $stmt_ins->execute([$u[0], $u[1], $u[2], $default_pass, $u[3]]);
    }
}
