<?php require_once __DIR__.'/bootstrap.php'; db(); $flash=get_flash(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ClientFlow — Simple account management</title><link rel="stylesheet" href="assets/style.css"></head><body>
<header class="sitebar"><a class="logo" href="index.php"><span>CF</span> ClientFlow</a><nav><a href="#features">Features</a><a href="#how">How it works</a><a href="feedback.php">Feedback</a><?php if(user_logged_in()):?><a href="account.php">Account</a><?php else:?><a href="login.php">Sign in</a><?php endif;?><a class="nav-cta" href="admin/login.php">Admin</a></nav></header>
<?php if($flash):?><div class="notice global <?=e($flash[0])?>"><?=e($flash[1])?></div><?php endif;?>
<main>
<section class="hero2"><div class="hero-left"><div class="mini-label">A simpler way to manage your account</div><h1>Everything you need,<br><em>without the clutter.</em></h1><p>Manage your account, keep your details current, and tell us what you think. A clean experience designed around the things that matter.</p><div class="hero-buttons"><a class="primary-btn" href="register.php">Get started <span>→</span></a><a class="secondary-btn" href="#features">See features</a></div><div class="trust"><span>✓ Easy account management</span><span>✓ Quick feedback</span><span>✓ Secure sign in</span></div></div>
<div class="visual"><div class="window"><div class="windowbar"><i></i><i></i><i></i><span>clientflow.app</span></div><div class="mock-head"><div><small>Welcome back</small><strong>Your account</strong></div><b class="online">Active</b></div><div class="mock-card"><small>PROFILE</small><h3>Personal information</h3><div class="mock-lines"><span></span><span></span></div></div><div class="mock-card"><small>ACCOUNT</small><h3>Manage your account</h3><div class="mock-actions"><b>Deactivate</b><b>Delete account</b></div></div></div></div></section>
<section id="features" class="feature-section"><div class="section-label">BUILT AROUND YOU</div><h2>A better account experience.</h2><div class="feature-grid"><article><span>01</span><h3>Simple profiles</h3><p>See your account details and status in one clear place.</p></article><article><span>02</span><h3>Flexible controls</h3><p>Deactivate temporarily or permanently delete your account when you choose.</p></article><article><span>03</span><h3>Open feedback</h3><p>Share feedback whenever something can be better. We actually make it easy to speak up.</p></article></div></section>
<section id="how" class="how"><div><div class="section-label">HOW IT WORKS</div><h2>Three simple steps.</h2></div><div class="how-list"><div><b>01</b><p><strong>Create your account</strong><br>Get started in under a minute.</p></div><div><b>02</b><p><strong>Manage it your way</strong><br>Review details or change your account status.</p></div><div><b>03</b><p><strong>Tell us what you think</strong><br>Share feedback at any point.</p></div></div></section>
</main><footer><div class="logo"><span>CF</span> ClientFlow</div><p>© <?=date('Y')?> ClientFlow. All rights reserved.</p></footer>
</body></html>
