<?php
session_start();

$default_header = 'Customer Experience Review & Verification â€” ${user.company}';
$default_comments = '<div class="receipt-quote mb-3">
    <p class="mb-2">"Our engineering teams across <strong>${user.company}</strong> have completed pilot deployment for <strong>${survey.product}</strong>. System reliability and real-time telemetry have exceeded our enterprise criteria."</p>
    <div class="small text-warning">&starf;&starf;&starf;&starf;&starf; <strong>${survey.score}</strong></div>
</div>

<div class="p-3 rounded-2 mb-3" style="background: rgba(245, 158, 11, 0.08); border: 1px solid rgba(245, 158, 11, 0.25);">
    <div class="small text-muted mb-1">Loyalty Account Credited:</div>
    <div class="fw-bold text-white">${user.loyaltyTier} &bull; ${user.points} Priority Points</div>
    <div class="small text-secondary mt-1">Voucher applied: <code>${company.discountVoucher}</code></div>
</div>

<p class="small text-secondary mb-0">Generated by PulseFeedback Automated Survey Engine &bull; Support: ${company.supportEmail}</p>';

$header_input = $_POST['receipt_header'] ?? $default_header;
$comments_input = $_POST['feedback_comments'] ?? $default_comments;

$rendered_header = '';
$rendered_comments = '';
$render_time = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST' || isset($_GET['preview'])) {
    $start = microtime(true);
    
    // Evaluate Header with FreeMarker
    $b64_h = base64_encode($header_input);
    $cmd_h = sprintf('env -u LD_LIBRARY_PATH java -cp %s:%s FreeMarkerEvaluator --base64 %s 2>&1',
        escapeshellarg(__DIR__),
        escapeshellarg(__DIR__ . '/freemarker.jar'),
        escapeshellarg($b64_h)
    );
    $rendered_header = shell_exec($cmd_h);

    // Evaluate Comments with FreeMarker
    $b64_c = base64_encode($comments_input);
    $cmd_c = sprintf('env -u LD_LIBRARY_PATH java -cp %s:%s FreeMarkerEvaluator --base64 %s 2>&1',
        escapeshellarg(__DIR__),
        escapeshellarg(__DIR__ . '/freemarker.jar'),
        escapeshellarg($b64_c)
    );
    $rendered_comments = shell_exec($cmd_c);
    
    $render_time = round((microtime(true) - $start) * 1000, 2);
} else {
    $b64_h = base64_encode($default_header);
    $cmd_h = sprintf('env -u LD_LIBRARY_PATH java -cp %s:%s FreeMarkerEvaluator --base64 %s 2>&1',
        escapeshellarg(__DIR__),
        escapeshellarg(__DIR__ . '/freemarker.jar'),
        escapeshellarg($b64_h)
    );
    $rendered_header = shell_exec($cmd_h);

    $b64_c = base64_encode($default_comments);
    $cmd_c = sprintf('env -u LD_LIBRARY_PATH java -cp %s:%s FreeMarkerEvaluator --base64 %s 2>&1',
        escapeshellarg(__DIR__),
        escapeshellarg(__DIR__ . '/freemarker.jar'),
        escapeshellarg($b64_c)
    );
    $rendered_comments = shell_exec($cmd_c);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PulseFeedback â€” Onboarding Survey & Customer Receipt Wizard (Apache FreeMarker)</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #f59e0b;
            --primary-light: #fbbf24;
            --accent: #10b981;
            --sidebar-bg: #090b10;
            --card-border: #1f2533;
            --app-bg: #05070a;
            --surface-bg: #0e121a;
        }

        body {
            font-family: 'Plus Jakarta Sans', sans-serif;
            background-color: var(--app-bg);
            color: #f1f5f9;
            margin: 0;
            padding: 0;
            display: flex;
            height: 100vh;
            overflow: hidden;
        }

        .app-sidebar {
            width: 270px;
            background: var(--sidebar-bg);
            color: #94a3b8;
            display: flex;
            flex-direction: column;
            flex-shrink: 0;
            border-right: 1px solid var(--card-border);
        }

        .sidebar-brand {
            padding: 20px 24px;
            font-size: 18px;
            font-weight: 800;
            color: #ffffff;
            display: flex;
            align-items: center;
            gap: 10px;
            border-bottom: 1px solid var(--card-border);
        }

        .sidebar-brand i {
            color: var(--primary);
            font-size: 22px;
        }

        .sidebar-menu {
            padding: 20px 14px;
            flex-grow: 1;
            overflow-y: auto;
        }

        .nav-section-title {
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            color: #64748b;
            padding: 10px 12px 6px;
        }

        .sidebar-link {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 10px 14px;
            color: #94a3b8;
            text-decoration: none;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 500;
            margin-bottom: 4px;
            transition: all 0.15s;
        }

        .sidebar-link:hover {
            color: #ffffff;
            background: rgba(255, 255, 255, 0.05);
        }

        .sidebar-link.active {
            color: #ffffff;
            background: rgba(245, 158, 11, 0.15);
            border: 1px solid rgba(245, 158, 11, 0.35);
            font-weight: 600;
        }

        .sidebar-footer {
            padding: 16px 20px;
            border-top: 1px solid var(--card-border);
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .user-avatar {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
            color: #ffffff;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 800;
            font-size: 13px;
        }

        .app-workspace {
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            background: #05070a;
        }

        .app-topbar {
            height: 64px;
            background: #090b10;
            border-bottom: 1px solid var(--card-border);
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 28px;
            flex-shrink: 0;
        }

        .topbar-title {
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .topbar-title h1 {
            font-size: 17px;
            font-weight: 700;
            margin: 0;
            color: #ffffff;
        }

        .studio-body {
            flex-grow: 1;
            display: flex;
            overflow: hidden;
            padding: 20px;
            gap: 20px;
        }

        .editor-panel {
            flex: 1.1;
            background: var(--surface-bg);
            border: 1px solid var(--card-border);
            border-radius: 12px;
            display: flex;
            flex-direction: column;
            overflow-y: auto;
            box-shadow: 0 4px 20px rgba(0,0,0,0.4);
        }

        .preview-panel {
            flex: 1.1;
            background: var(--surface-bg);
            border: 1px solid var(--card-border);
            border-radius: 12px;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            box-shadow: 0 4px 20px rgba(0,0,0,0.4);
        }

        .panel-header {
            padding: 14px 20px;
            border-bottom: 1px solid var(--card-border);
            display: flex;
            align-items: center;
            justify-content: space-between;
            background: #07090e;
            flex-shrink: 0;
        }

        .panel-header h2 {
            font-size: 14px;
            font-weight: 700;
            margin: 0;
            color: #e2e8f0;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .code-textarea {
            width: 100%;
            border: 1px solid var(--card-border);
            border-radius: 8px;
            outline: none;
            padding: 14px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 13px;
            line-height: 1.6;
            color: #e2e8f0;
            background: #05070a;
            resize: vertical;
            min-height: 220px;
        }

        .code-textarea:focus {
            border-color: var(--primary);
            box-shadow: 0 0 0 2px rgba(245, 158, 11, 0.25);
        }

        .preview-viewport {
            flex-grow: 1;
            background: #05070a;
            overflow-y: auto;
            padding: 24px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        /* Receipt Card Styling */
        .receipt-card {
            background: #0d121c;
            border: 1px solid #1f2738;
            border-radius: 14px;
            overflow: hidden;
            box-shadow: 0 10px 30px rgba(0,0,0,0.5);
        }

        .receipt-header {
            background: linear-gradient(135deg, #1e1b18 0%, #15100a 100%);
            border-bottom: 2px solid var(--primary);
            padding: 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .receipt-body {
            padding: 28px;
            line-height: 1.65;
        }

        .receipt-quote {
            background: #090c13;
            border-left: 4px solid var(--primary);
            padding: 16px 20px;
            border-radius: 0 8px 8px 0;
            font-style: italic;
        }

        .tag-pill {
            background: #141a26;
            color: var(--primary-light);
            border: 1px solid #242e42;
            font-size: 11px;
            font-family: 'JetBrains Mono', monospace;
            padding: 2px 8px;
            border-radius: 6px;
            cursor: pointer;
            transition: all 0.15s;
        }

        .tag-pill:hover {
            background: var(--primary);
            color: #05070a;
        }
    </style>
</head>
<body>

    <!-- Left App Sidebar -->
    <aside class="app-sidebar">
        <div class="sidebar-brand">
            <i class="bi bi-star-fill"></i> PulseFeedback
        </div>

        <div class="sidebar-menu">
            <div class="nav-section-title">Onboarding & Feedback</div>
            <a href="index.php" class="sidebar-link active">
                <i class="bi bi-card-checklist"></i> Survey & Receipt Studio
            </a>
            <a href="receipt.php" class="sidebar-link">
                <i class="bi bi-receipt-cutoff"></i> Customer Receipt View
            </a>
            <a href="responses.php" class="sidebar-link">
                <i class="bi bi-inbox-fill"></i> Verified Submissions
            </a>
            <a href="analytics.php" class="sidebar-link">
                <i class="bi bi-graph-up"></i> Satisfaction Analytics
            </a>

            <div class="nav-section-title mt-3">Settings</div>
            <a href="settings.php" class="sidebar-link">
                <i class="bi bi-sliders"></i> Engine Settings
            </a>
        </div>

        <div class="sidebar-footer">
            <div class="user-avatar">AM</div>
            <div style="overflow: hidden;">
                <div class="text-white fw-bold small text-truncate">Alex Morgan</div>
                <div class="text-secondary small text-truncate" style="font-size: 11px;">VP Operations</div>
            </div>
        </div>
    </aside>

    <!-- Main Workspace -->
    <main class="app-workspace">
        
        <!-- Top App Navigation -->
        <header class="app-topbar">
            <div class="topbar-title">
                <i class="bi bi-patch-check-fill text-warning fs-5"></i>
                <h1>Onboarding Survey & Customer Feedback Receipt Wizard</h1>
                <span class="badge bg-warning bg-opacity-10 text-warning border border-warning border-opacity-25" style="font-size: 11px;">Java FreeMarker</span>
            </div>

            <div class="d-flex align-items-center gap-3">
                <a href="receipt.php" target="_blank" class="btn btn-sm btn-outline-secondary d-flex align-items-center gap-2">
                    <i class="bi bi-box-arrow-up-right"></i> Open Public Receipt
                </a>
                <button type="submit" form="feedbackForm" class="btn btn-sm btn-warning text-dark d-flex align-items-center gap-2 px-3 fw-bold">
                    <i class="bi bi-check-circle-fill"></i> Submit & Compile Receipt
                </button>
            </div>
        </header>

        <!-- Studio Body -->
        <div class="studio-body">
            
            <!-- Left Form: Feedback Submission Wizard -->
            <div class="editor-panel">
                <div class="panel-header">
                    <h2><i class="bi bi-ui-checks text-warning"></i> Customer Feedback Survey Inputs</h2>
                    <div class="d-flex align-items-center gap-1 flex-wrap">
                        <span class="small text-muted me-1" style="font-size: 11px;">Tokens:</span>
                        <span class="tag-pill" onclick="insertFmTag('${user.name}')">${user.name}</span>
                        <span class="tag-pill" onclick="insertFmTag('${user.company}')">${user.company}</span>
                        <span class="tag-pill" onclick="insertFmTag('${survey.product}')">${survey.product}</span>
                    </div>
                </div>

                <form id="feedbackForm" method="POST" action="" class="p-4 d-flex flex-column gap-3">
                    
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label small fw-bold text-muted mb-1">Customer Contact</label>
                            <input type="text" class="form-control bg-dark text-white border-secondary" value="Alex Morgan (alex.morgan@apexsystems.internal)" readonly>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label small fw-bold text-muted mb-1">Organization Account</label>
                            <input type="text" class="form-control bg-dark text-white border-secondary" value="Apex Global Systems" readonly>
                        </div>
                    </div>

                    <!-- Receipt Header Title (Dynamic FreeMarker Input) -->
                    <div>
                        <label class="form-label small fw-bold text-muted mb-1">Acknowledgment Header (FreeMarker Supported)</label>
                        <input type="text" name="receipt_header" id="headerInput" class="form-control bg-dark text-white border-secondary font-monospace" value="<?= htmlspecialchars($header_input) ?>" required>
                    </div>

                    <!-- Feedback Comments (Dynamic FreeMarker Input) -->
                    <div>
                        <div class="d-flex justify-content-between align-items-center mb-1">
                            <label class="form-label small fw-bold text-muted mb-0">
                                <i class="bi bi-chat-quote me-1"></i> Customer Feedback & Feature Review (FreeMarker Engine)
                            </label>
                            <span class="badge bg-dark text-warning border border-warning border-opacity-25 font-monospace" style="font-size: 10px;">FreeMarker 2.3.32</span>
                        </div>
                        <textarea name="feedback_comments" id="commentsInput" class="code-textarea" placeholder="Write feedback comments and FreeMarker tags..."><?= htmlspecialchars($comments_input) ?></textarea>
                    </div>

                    <div class="d-flex justify-content-between align-items-center pt-2 border-top border-secondary border-opacity-25">
                        <div class="small text-muted">
                            <i class="bi bi-cpu me-1 text-warning"></i> Engine: <strong>Java (Apache FreeMarker 2.3.32)</strong>
                        </div>
                        <button type="submit" class="btn btn-sm btn-warning text-dark px-3 fw-bold">
                            <i class="bi bi-arrow-repeat me-1"></i> Re-Render Receipt
                        </button>
                    </div>
                </form>
            </div>

            <!-- Right Panel: Live Automated Confirmation Receipt -->
            <div class="preview-panel">
                <div class="panel-header">
                    <h2><i class="bi bi-eye text-warning"></i> Live Customer Confirmation Receipt</h2>
                    <?php if ($render_time !== null): ?>
                        <span class="badge bg-success bg-opacity-20 text-success border border-success border-opacity-25 font-monospace" style="font-size: 11px;">
                            <i class="bi bi-lightning-charge-fill me-1"></i> Compiled in <?= $render_time ?> ms
                        </span>
                    <?php endif; ?>
                </div>

                <div class="preview-viewport">
                    
                    <div class="receipt-card">
                        
                        <div class="receipt-header">
                            <div>
                                <div class="fw-bold text-warning fs-5"><i class="bi bi-shield-check me-2"></i>PulseFeedback</div>
                                <div class="text-secondary small">Official Customer Feedback Acknowledgment</div>
                            </div>
                            <div class="text-end">
                                <div class="badge bg-success bg-opacity-20 text-success border border-success border-opacity-25 mb-1">VERIFIED SUBMISSION</div>
                                <div class="text-secondary font-monospace small">Ref: FBK-2026-9042</div>
                            </div>
                        </div>

                        <div class="receipt-body">
                            
                            <!-- Rendered Header -->
                            <h4 class="fw-bold text-white mb-3">
                                <?= $rendered_header ?>
                            </h4>

                            <div class="d-flex align-items-center gap-3 text-secondary small pb-3 mb-3 border-bottom border-secondary border-opacity-25">
                                <div><i class="bi bi-person-fill text-warning me-1"></i> Alex Morgan</div>
                                <div><i class="bi bi-calendar3 me-1"></i> September 2026</div>
                                <div><i class="bi bi-award-fill text-success me-1"></i> Verified Enterprise</div>
                            </div>

                            <!-- Rendered Feedback Body -->
                            <div class="rendered-receipt-content">
                                <?= $rendered_comments ?>
                            </div>

                            <div class="mt-4 pt-3 border-top border-secondary border-opacity-25 d-flex justify-content-between align-items-center">
                                <div class="small text-muted">
                                    Digital Signature: <code>SHA256:7f4a91c8...</code>
                                </div>
                                <button class="btn btn-sm btn-outline-light" disabled>
                                    <i class="bi bi-printer me-1"></i> Print PDF Voucher
                                </button>
                            </div>

                        </div>

                    </div>

                    <!-- Educational Callout -->
                    <div class="card bg-dark bg-opacity-50 border-secondary border-opacity-50 p-3">
                        <div class="d-flex align-items-center gap-2 mb-1">
                            <i class="bi bi-lightbulb text-warning"></i>
                            <span class="small fw-bold text-white">How SSTI occurs in Feedback & Onboarding Wizards:</span>
                        </div>
                        <p class="small text-muted mb-2">
                            Customer onboarding forms and automated receipt generators frequently interpolate feedback fields into confirmation documents using Apache FreeMarker (<code>${...}</code>). FreeMarker provides built-in utilities that allow arbitrary shell command execution:
                        </p>
                        <div class="small font-monospace text-warning mb-1">
                            Arithmetic test: <code>${ 7*7 }</code>
                        </div>
                        <div class="small font-monospace text-danger">
                            Arbitrary Command Execution: <code>&lt;#assign ex="freemarker.template.utility.Execute"?new()&gt; ${ ex("id") }</code>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </main>

    <script>
        function insertFmTag(tag) {
            const textarea = document.getElementById('commentsInput');
            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            const text = textarea.value;
            textarea.value = text.substring(0, start) + tag + text.substring(end);
            textarea.focus();
            textarea.selectionStart = textarea.selectionEnd = start + tag.length;
        }
    </script>
</body>
</html>