<?php
declare(strict_types=1); session_start();
const DB_HOST='127.0.0.1'; const DB_PORT='3306'; const DB_NAME='deskflow'; const DB_USER='root'; const DB_PASS='';
const SITE_NAME='DeskFlow'; const ADMIN_EMAIL='admin@deskflow.local'; const ADMIN_PASSWORD='admin';
function db():PDO{static $p=null;if($p)return$p;$s=new PDO("mysql:host=".DB_HOST.";port=".DB_PORT.";charset=utf8mb4",DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$s->exec("CREATE DATABASE IF NOT EXISTS `".DB_NAME."` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$p=new PDO("mysql:host=".DB_HOST.";port=".DB_PORT.";dbname=".DB_NAME.";charset=utf8mb4",DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$p->exec("CREATE TABLE IF NOT EXISTS tickets(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_no VARCHAR(32) UNIQUE NOT NULL,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,subject VARCHAR(255) NOT NULL,category VARCHAR(80) NOT NULL,priority ENUM('low','normal','high','urgent') DEFAULT 'normal',message TEXT NOT NULL,status ENUM('open','pending','solved','closed') DEFAULT 'open',agent_reply TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$p->exec("CREATE TABLE IF NOT EXISTS articles(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,category VARCHAR(80) NOT NULL,excerpt VARCHAR(500) NOT NULL,content TEXT NOT NULL,views INT UNSIGNED DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$p->exec("CREATE TABLE IF NOT EXISTS admins(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$q=$p->prepare("SELECT id FROM admins WHERE email=?");$q->execute([ADMIN_EMAIL]);if(!$q->fetch()){$q=$p->prepare("INSERT INTO admins(email,password_hash) VALUES(?,?)");$q->execute([ADMIN_EMAIL,password_hash(ADMIN_PASSWORD,PASSWORD_DEFAULT)]);}
if((int)$p->query("SELECT COUNT(*) FROM articles")->fetchColumn()===0){$seed=[['How do I reset my password?','Account','Change your password in a few quick steps.','Open your account settings, choose Security, then select Change password. Enter your current password and a new password, then save your changes.'],['Where can I find my invoices?','Billing','Find invoices and payment history from your account.','Open Billing from your account menu. Your latest invoice appears first, and older invoices are available in the payment history section.'],['Why is my account locked?','Account','Common reasons an account can be temporarily locked.','Several unsuccessful sign-in attempts can temporarily lock an account. Wait a few minutes and try again. If the problem continues, submit a support request.'],['Troubleshooting a technical issue','Technical','A simple checklist before contacting support.','Refresh the page, sign out and back in, and try another browser or private window. Include the exact error message in your request if the issue continues.'],['Contacting the support team','Getting started','What information helps us resolve requests faster.','Include a clear subject, what you expected to happen, what happened instead, and any relevant steps. This helps our team route and resolve your request faster.'],['Understanding request statuses','Getting started','What each support status means.','Open means the team is reviewing your request. Pending means we need more information or are waiting on another step. Solved means the issue has been answered. Closed means the request is complete.']];$i=$p->prepare("INSERT INTO articles(title,category,excerpt,content) VALUES(?,?,?,?)");foreach($seed as $a)$i->execute($a);}
return$p;}db();
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function csrf():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));return $_SESSION['csrf'];}
function verify():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Invalid request.');}}
function admin():void{if(empty($_SESSION['admin'])){header('Location: login.php');exit;}}
function ticket_no():string{return 'DF-'.strtoupper(bin2hex(random_bytes(4)));}
function flash($m=null){if($m!==null){$_SESSION['flash']=$m;return null;}$x=$_SESSION['flash']??null;unset($_SESSION['flash']);return$x;}
?>