<?php
session_start();

$default_subject = '[{{incident["severity"]}}] {{incident["summary"]}} on {{node["hostname"]}}';
$default_body = '<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; padding: 20px; color: #e2e8f0; margin: 0; }
  .alert-card { max-width: 650px; margin: 0 auto; background: #1e293b; border-radius: 12px; border: 1px solid #334155; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }
  .alert-header { background: #dc2626; color: #ffffff; padding: 20px 24px; display: flex; justify-content: space-between; align-items: center; }
  .alert-title { font-size: 16px; font-weight: 800; letter-spacing: -0.3px; }
  .alert-body { padding: 24px; }
  .metric-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 20px 0; }
  .metric-card { background: #0f172a; border: 1px solid #334155; border-radius: 8px; padding: 12px; }
  .metric-label { font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; margin-bottom: 4px; }
  .metric-val { font-size: 16px; font-weight: 700; color: #f8fafc; font-family: monospace; }
  .info-table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 14px; }
  .info-table td { padding: 8px 0; border-bottom: 1px solid #334155; }
  .info-table td:first-child { color: #94a3b8; width: 130px; font-weight: 600; }
  .btn-ack { display: inline-block; background: #2563eb; color: #ffffff !important; padding: 10px 22px; border-radius: 6px; font-weight: 600; text-decoration: none; font-size: 13px; margin-top: 18px; }
  .alert-footer { background: #0f172a; padding: 14px 24px; font-size: 11px; color: #64748b; border-top: 1px solid #334155; text-align: center; }
</style>
</head>
<body>
  <div class="alert-card">
    <div class="alert-header">
      <div class="alert-title"><i class="bi bi-exclamation-triangle-fill me-2"></i> {{incident["severity"]}} Alert</div>
      <div style="font-size: 12px; opacity: 0.9; font-family: monospace;">{{incident["id"]}}</div>
    </div>

    <div class="alert-body">
      <h3 style="margin: 0 0 8px 0; font-size: 18px; color: #f8fafc;">{{incident["summary"]}}</h3>
      <p style="font-size: 13px; color: #94a3b8; margin: 0 0 16px 0;">Automated trigger dispatched to on-call engineer <strong>{{user["name"]}}</strong> ({{user["role"]}}).</p>

      <div class="metric-grid">
        <div class="metric-card">
          <div class="metric-label">P99 Latency</div>
          <div class="metric-val" style="color: #f87171;">{{metric["latency_p99"]}}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Throughput</div>
          <div class="metric-val" style="color: #38bdf8;">{{metric["throughput"]}}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">CPU Load</div>
          <div class="metric-val" style="color: #fbbf24;">{{metric["cpu_load"]}}</div>
        </div>
      </div>

      <table class="info-table">
        <tr>
          <td>Affected Node</td>
          <td><strong>{{node["hostname"]}}</strong> ({{node["ip"]}})</td>
        </tr>
        <tr>
          <td>Cloud Region</td>
          <td>{{node["region"]}}</td>
        </tr>
        <tr>
          <td>Status &amp; Uptime</td>
          <td><span style="color: #f87171; font-weight: bold;">{{node["status"]}}</span> &bull; {{node["uptime"]}}</td>
        </tr>
        <tr>
          <td>Event Timestamp</td>
          <td>{{incident["timestamp"]}}</td>
        </tr>
      </table>

      <center>
        <a href="#" class="btn-ack">Acknowledge Incident in PagerDuty &rarr;</a>
      </center>
    </div>

    <div class="alert-footer">
      Generated by {{app_title}} &bull; Python Async Microservice Event Pipeline
    </div>
  </div>
</body>
</html>';

$subject_input = $_POST['subject'] ?? $default_subject;
$body_input = $_POST['body'] ?? $default_body;

$rendered_subject = '';
$rendered_body = '';
$render_time = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST' || isset($_GET['preview'])) {
    $start = microtime(true);
    
    // Evaluate Subject
    $b64_sub = base64_encode($subject_input);
    $cmd_sub = sprintf(
        'python3 %s %s 2>&1',
        escapeshellarg(__DIR__ . '/evaluator.py'),
        escapeshellarg($b64_sub)
    );
    $rendered_subject = shell_exec($cmd_sub);

    // Evaluate Body
    $b64_body = base64_encode($body_input);
    $cmd_body = sprintf(
        'python3 %s %s 2>&1',
        escapeshellarg(__DIR__ . '/evaluator.py'),
        escapeshellarg($b64_body)
    );
    $rendered_body = shell_exec($cmd_body);
    
    $render_time = round((microtime(true) - $start) * 1000, 2);
} else {
    $b64_sub = base64_encode($default_subject);
    $rendered_subject = shell_exec(sprintf('python3 %s %s 2>&1', escapeshellarg(__DIR__ . '/evaluator.py'), escapeshellarg($b64_sub)));

    $b64_body = base64_encode($default_body);
    $rendered_body = shell_exec(sprintf('python3 %s %s 2>&1', escapeshellarg(__DIR__ . '/evaluator.py'), escapeshellarg($b64_body)));
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TornadoAlert — Python SRE Incident & Webhook Dispatch Studio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #06b6d4;
            --primary-dark: #0891b2;
            --sidebar-bg: #090d16;
            --card-border: #1e293b;
            --app-bg: #0f172a;
        }

        body {
            font-family: 'Space Grotesk', sans-serif;
            background-color: var(--app-bg);
            color: #f1f5f9;
            margin: 0;
            padding: 0;
            display: flex;
            height: 100vh;
            overflow: hidden;
        }

        .app-sidebar {
            width: 260px;
            background: var(--sidebar-bg);
            color: #94a3b8;
            display: flex;
            flex-direction: column;
            flex-shrink: 0;
            border-right: 1px solid #1e293b;
        }

        .sidebar-brand {
            padding: 20px 24px;
            font-size: 18px;
            font-weight: 700;
            color: #ffffff;
            display: flex;
            align-items: center;
            gap: 10px;
            border-bottom: 1px solid #1e293b;
        }

        .sidebar-brand i {
            color: #06b6d4;
            font-size: 22px;
        }

        .sidebar-menu {
            padding: 20px 14px;
            flex-grow: 1;
            overflow-y: auto;
        }

        .nav-section-title {
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            color: #64748b;
            padding: 10px 12px 6px;
        }

        .sidebar-link {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 10px 14px;
            color: #94a3b8;
            text-decoration: none;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 500;
            margin-bottom: 4px;
            transition: all 0.15s;
        }

        .sidebar-link:hover {
            color: #ffffff;
            background: rgba(255, 255, 255, 0.05);
        }

        .sidebar-link.active {
            color: #ffffff;
            background: rgba(6, 182, 212, 0.15);
            border: 1px solid rgba(6, 182, 212, 0.3);
            font-weight: 600;
        }

        .sidebar-footer {
            padding: 16px 20px;
            border-top: 1px solid #1e293b;
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .user-avatar {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: #0891b2;
            color: #ffffff;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 700;
            font-size: 13px;
        }

        .app-workspace {
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            background: #0b1120;
        }

        .app-topbar {
            height: 64px;
            background: #0f172a;
            border-bottom: 1px solid var(--card-border);
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 28px;
            flex-shrink: 0;
        }

        .topbar-title {
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .topbar-title h1 {
            font-size: 17px;
            font-weight: 700;
            margin: 0;
            color: #ffffff;
        }

        .studio-body {
            flex-grow: 1;
            display: flex;
            overflow: hidden;
            padding: 20px;
            gap: 20px;
        }

        .editor-panel {
            flex: 1;
            background: #111827;
            border: 1px solid var(--card-border);
            border-radius: 12px;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            box-shadow: 0 4px 20px rgba(0,0,0,0.3);
        }

        .panel-header {
            padding: 14px 20px;
            border-bottom: 1px solid var(--card-border);
            display: flex;
            align-items: center;
            justify-content: space-between;
            background: #0d1322;
        }

        .panel-header h2 {
            font-size: 14px;
            font-weight: 700;
            margin: 0;
            color: #e2e8f0;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .code-textarea {
            width: 100%;
            flex-grow: 1;
            border: none;
            outline: none;
            padding: 16px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 13px;
            line-height: 1.6;
            color: #e2e8f0;
            background: #111827;
            resize: none;
        }

        .preview-panel {
            flex: 1;
            background: #111827;
            border: 1px solid var(--card-border);
            border-radius: 12px;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            box-shadow: 0 4px 20px rgba(0,0,0,0.3);
        }

        .preview-viewport {
            flex-grow: 1;
            background: #090d16;
            overflow-y: auto;
            padding: 24px;
            display: flex;
            flex-direction: column;
        }

        .email-meta-header {
            background: #1e293b;
            border: 1px solid var(--card-border);
            border-radius: 8px;
            padding: 14px 18px;
            margin-bottom: 18px;
            font-size: 13px;
        }

        .email-meta-row {
            display: flex;
            margin-bottom: 6px;
        }

        .email-meta-row:last-child {
            margin-bottom: 0;
        }

        .email-meta-label {
            width: 85px;
            color: #94a3b8;
            font-weight: 600;
        }

        .email-meta-value {
            color: #f8fafc;
            font-weight: 500;
        }

        .rendered-container {
            background: #1e293b;
            border: 1px solid var(--card-border);
            border-radius: 8px;
            padding: 20px;
            flex-grow: 1;
            min-height: 400px;
        }

        .tag-pill {
            background: #1e293b;
            color: #38bdf8;
            border: 1px solid #334155;
            font-size: 11px;
            font-family: 'JetBrains Mono', monospace;
            padding: 2px 8px;
            border-radius: 6px;
            cursor: pointer;
            transition: all 0.15s;
        }

        .tag-pill:hover {
            background: #0284c7;
            color: #ffffff;
        }
    </style>
</head>
<body>

    <!-- Left App Sidebar -->
    <aside class="app-sidebar">
        <div class="sidebar-brand">
            <i class="bi bi-lightning-charge-fill"></i> TornadoAlert
        </div>

        <div class="sidebar-menu">
            <div class="nav-section-title">Telemetry & Incident Response</div>
            <a href="index.php" class="sidebar-link active">
                <i class="bi bi-bell-fill text-cyan"></i> Alert Studio
            </a>
            <a href="incidents.php" class="sidebar-link">
                <i class="bi bi-activity"></i> Active Incidents
            </a>
            <a href="nodes.php" class="sidebar-link">
                <i class="bi bi-hdd-network"></i> Edge Nodes
            </a>
            <a href="metrics.php" class="sidebar-link">
                <i class="bi bi-speedometer2"></i> Telemetry & Metrics
            </a>

            <div class="nav-section-title mt-3">Platform Configuration</div>
            <a href="settings.php" class="sidebar-link">
                <i class="bi bi-sliders"></i> Engine Settings
            </a>
        </div>

        <div class="sidebar-footer">
            <div class="user-avatar">ER</div>
            <div>
                <div class="text-white fw-bold small">Elena Rostova</div>
                <div class="text-secondary small" style="font-size: 11px;">Principal SRE (On-Call)</div>
            </div>
        </div>
    </aside>

    <!-- Main Workspace -->
    <main class="app-workspace">
        
        <!-- Top Navigation -->
        <header class="app-topbar">
            <div class="topbar-title">
                <i class="bi bi-broadcast text-cyan fs-5"></i>
                <h1>Webhook & Incident Notification Template Studio</h1>
                <span class="badge bg-info bg-opacity-10 text-info border border-info border-opacity-25" style="font-size: 11px;">Tornado 6.4 Async</span>
            </div>

            <div class="d-flex align-items-center gap-3">
                <button type="button" class="btn btn-sm btn-outline-secondary d-flex align-items-center gap-2" onclick="document.getElementById('tornadoForm').reset();">
                    <i class="bi bi-arrow-counterclockwise"></i> Reset
                </button>
                <button type="button" class="btn btn-sm btn-outline-info d-flex align-items-center gap-2" onclick="alert('Synthetic test alert fired to PagerDuty!');">
                    <i class="bi bi-send-check"></i> Fire Synthetic Alert
                </button>
                <button type="submit" form="tornadoForm" class="btn btn-sm btn-info text-white d-flex align-items-center gap-2 px-3 fw-semibold">
                    <i class="bi bi-play-circle-fill"></i> Render & Preview
                </button>
            </div>
        </header>

        <!-- Studio Body -->
        <div class="studio-body">
            
            <!-- Left Form & Code Editor -->
            <div class="editor-panel">
                <form id="tornadoForm" method="POST" action="" style="display: flex; flex-direction: column; height: 100%;">
                    <div class="panel-header">
                        <h2><i class="bi bi-code-square text-info"></i> Tornado Template Source & Tokens</h2>
                        <div class="d-flex align-items-center gap-1 flex-wrap">
                            <span class="small text-muted me-1" style="font-size: 11px;">Tokens:</span>
                            <span class="tag-pill" onclick="insertTag('{{user["name"]}}')">{{user["name"]}}</span>
                            <span class="tag-pill" onclick="insertTag('{{node["hostname"]}}')">{{node["hostname"]}}</span>
                            <span class="tag-pill" onclick="insertTag('{{metric["latency_p99"]}}')">{{metric["latency_p99"]}}</span>
                        </div>
                    </div>

                    <!-- Subject / Header Bar -->
                    <div class="p-3 border-bottom border-dark bg-black bg-opacity-25">
                        <label class="form-label small fw-bold text-muted mb-1">Alert Headline / Push Notification Title</label>
                        <div class="input-group input-group-sm">
                            <span class="input-group-text bg-dark text-muted border-secondary"><i class="bi bi-chat-left-dots"></i></span>
                            <input type="text" name="subject" id="subjectInput" class="form-control bg-dark text-white border-secondary font-monospace" value="<?= htmlspecialchars($subject_input) ?>" placeholder="Enter alert subject with Tornado {{...}} tokens...">
                        </div>
                    </div>

                    <!-- Template Code Area -->
                    <div class="d-flex flex-column flex-grow-1">
                        <textarea name="body" id="bodyInput" class="code-textarea" placeholder="Write dynamic Tornado template code..."><?= htmlspecialchars($body_input) ?></textarea>
                    </div>

                    <div class="p-3 border-top border-dark bg-black bg-opacity-25 d-flex justify-content-between align-items-center">
                        <div class="small text-muted">
                            <i class="bi bi-cpu me-1 text-info"></i> Engine: <strong>Python 3.12 (Tornado Template Parser)</strong>
                        </div>
                        <button type="submit" class="btn btn-sm btn-info text-white px-3 fw-semibold">
                            <i class="bi bi-arrow-repeat me-1"></i> Re-Render Notification
                        </button>
                    </div>
                </form>
            </div>

            <!-- Right Preview Panel -->
            <div class="preview-panel">
                <div class="panel-header">
                    <h2><i class="bi bi-eye text-info"></i> Dispatch Simulation View</h2>
                    <div class="btn-group btn-group-sm" role="group">
                        <button type="button" class="btn btn-outline-secondary active"><i class="bi bi-slack me-1"></i> Webhook View</button>
                        <button type="button" class="btn btn-outline-secondary"><i class="bi bi-envelope me-1"></i> Email View</button>
                    </div>
                </div>

                <div class="preview-viewport">
                    
                    <!-- Simulated Dispatch Headers -->
                    <div class="email-meta-header">
                        <div class="email-meta-row">
                            <div class="email-meta-label">Origin:</div>
                            <div class="email-meta-value">TornadoAlert Telemetry Daemon &lt;alerts@tornado-cloud.io&gt;</div>
                        </div>
                        <div class="email-meta-row">
                            <div class="email-meta-label">Subscriber:</div>
                            <div class="email-meta-value">Elena Rostova (On-Call SRE)</div>
                        </div>
                        <div class="email-meta-row">
                            <div class="email-meta-label">Headline:</div>
                            <div class="email-meta-value fw-bold text-info"><?= htmlspecialchars($rendered_subject) ?></div>
                        </div>
                    </div>

                    <!-- Rendered HTML Payload Canvas -->
                    <div class="rendered-container">
                        <?= $rendered_body ?>
                    </div>
                </div>
            </div>

        </div>
    </main>

    <script>
        function insertTag(tag) {
            const textarea = document.getElementById('bodyInput');
            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            const text = textarea.value;
            textarea.value = text.substring(0, start) + tag + text.substring(end);
            textarea.focus();
            textarea.selectionStart = textarea.selectionEnd = start + tag.length;
        }
    </script>
</body>
</html>
