<?php
require_once __DIR__.'/../config.php'; require_admin();
$id=(int)($_GET['id']??0);$s=db()->prepare("SELECT * FROM reports WHERE id=?");$s->execute([$id]);$r=$s->fetch();if(!$r)exit('Case not found.');
$s=db()->prepare("SELECT * FROM report_notes WHERE report_id=? ORDER BY created_at DESC");$s->execute([$id]);$notes=$s->fetchAll();
$s=db()->prepare("SELECT * FROM report_events WHERE report_id=? ORDER BY created_at DESC");$s->execute([$id]);$events=$s->fetchAll();
$title='Case '.$r['case_no']; ?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> · TrustDesk</title><link rel="stylesheet" href="../assets/style.css"></head><body class="admin-shell">
<header class="admin-top"><a class="brand" href="../index.php"><span class="shield">✦</span>TrustDesk</a><div><a href="index.php">← Queue</a><a href="logout.php">Sign out</a></div></header>
<main class="case-admin"><div class="case-admin-head"><div><span class="eyebrow"><?=e($r['case_no'])?></span><h1><?=e($r['title'])?></h1></div><span class="status status-<?=e($r['status'])?>"><?=e(str_replace('_',' ',$r['status']))?></span></div>
<div class="admin-columns"><section class="case-card"><h3>Report details</h3><dl><dt>Type</dt><dd><?=e(ucfirst($r['report_type']))?></dd><dt>Severity</dt><dd><?=e(ucfirst($r['severity']))?></dd><dt>Reporter</dt><dd><?=e($r['anonymous']?'Anonymous':($r['reporter_name']?:'Not provided'))?> <?= $r['reporter_email']?' · '.e($r['reporter_email']):''?></dd><dt>Target</dt><dd><?=e($r['target_username']?:'Not provided')?> <?= $r['target_url']?' · '.e($r['target_url']):''?></dd><dt>Submitted</dt><dd><?=e($r['created_at'])?></dd></dl><hr><h3>Description</h3><p><?=nl2br(e($r['description']))?></p><?php if($r['evidence']):?><h3>Evidence / context</h3><p><?=nl2br(e($r['evidence']))?></p><?php endif;?></section>
<aside><form class="case-card" action="update.php" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$id?>"><h3>Case action</h3><label>Status<select name="status"><?php foreach(['new','investigating','action_required','resolved','closed'] as $v):?><option <?=$r['status']===$v?'selected':''?> value="<?=$v?>"><?=ucfirst(str_replace('_',' ',$v))?></option><?php endforeach;?></select></label><label>Severity<select name="severity"><?php foreach(['low','medium','high','critical'] as $v):?><option <?=$r['severity']===$v?'selected':''?> value="<?=$v?>"><?=ucfirst($v)?></option><?php endforeach;?></select></label><label>Customer-facing response<textarea name="admin_response" rows="6"><?=e($r['admin_response'])?></textarea></label><button class="button dark wide">Save case update</button></form>
<form class="case-card" action="update.php" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="note"><h3>Internal note</h3><textarea name="note" rows="4" required placeholder="Only staff can see this note"></textarea><button class="button wide">Add note</button></form></aside></div>
<section class="history"><h3>Case activity</h3><?php foreach($events as $ev):?><div><span>•</span><p><?=e($ev['event_text'])?><small><?=e($ev['created_at'])?></small></p></div><?php endforeach;?><?php foreach($notes as $n):?><div><span>✎</span><p><?=nl2br(e($n['note']))?><small>Internal note · <?=e($n['created_at'])?></small></p></div><?php endforeach;?></section>
</main></body></html>