<?php
$id=(int)($_GET['id']??0);$st=db()->prepare("SELECT * FROM disputes WHERE id=?");$st->bind_param('i',$id);$st->execute();$c=one($st);if(!$c)die('Case not found.');
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$status=$_POST['status']??$c['status'];$priority=$_POST['priority']??$c['priority'];$response=trim($_POST['admin_response']??'');$public=trim($_POST['public_note']??'');$allowedS=['submitted','under_review','awaiting_response','resolved','closed','rejected'];$allowedP=['low','normal','high','urgent'];if(!in_array($status,$allowedS,true)||!in_array($priority,$allowedP,true))die('Invalid case update.');$u=db()->prepare("UPDATE disputes SET status=?,priority=?,admin_response=? WHERE id=?");$u->bind_param('sssi',$status,$priority,$response,$id);$u->execute();if($public){$ev=db()->prepare("INSERT INTO dispute_events(dispute_id,event_text,public_note) VALUES(?,?,?)");$text='Case updated to '.label($status);$ev->bind_param('iss',$id,$text,$public);$ev->execute();}header('Location:case.php?id='.$id);exit;}
$e=db()->prepare("SELECT * FROM evidence WHERE dispute_id=? ORDER BY created_at");$e->bind_param('i',$id);$e->execute();$evidence=rows($e);$ev=db()->prepare("SELECT * FROM dispute_events WHERE dispute_id=? ORDER BY created_at DESC");$ev->bind_param('i',$id);$ev->execute();$events=rows($ev);$title='Case '.$c['case_no'];require 'header.php';?>
<div class="admin-head"><div><a class="back" href="cases.php">← All cases</a><div class="kicker"><span></span> <?=h($c['case_no'])?></div><h1><?=h($c['dispute_type'])?></h1><p><?=h($c['claimant_name'])?> · <?=h($c['claimant_email'])?></p></div><span class="status <?=h($c['status'])?>"><?=h(label($c['status']))?></span></div>
<div class="case-admin-grid"><div>
<section class="admin-panel"><h2>Claim details</h2><div class="facts"><div><small>Transaction</small><b><?=h($c['transaction_ref']?:'—')?></b></div><div><small>Amount</small><b><?=h($c['currency'])?> <?=number_format((float)$c['amount'],2)?></b></div><div><small>Company</small><b><?=h($c['company']?:'—')?></b></div><div><small>Requested</small><b><?=h($c['desired_resolution']?:'—')?></b></div></div><h3>Description</h3><p class="case-text"><?=nl2br(h($c['description']))?></p><h3>Evidence summary</h3><p class="case-text"><?=nl2br(h($c['evidence_summary']?:'No summary provided.'))?></p></section>
<section class="admin-panel"><h2>Evidence files</h2><?php if(!$evidence):?><p>No files attached.</p><?php else:foreach($evidence as $f):?><div class="file-row"><span>▧</span><div><b><?=h($f['original_name'])?></b><small><?=number_format($f['file_size']/1024,1)?> KB</small></div><a href="../uploads/<?=h($f['stored_name'])?>" target="_blank">Open</a></div><?php endforeach;endif;?></section>
<section class="admin-panel"><h2>Public timeline</h2><?php foreach($events as $x):?><div class="admin-event"><b><?=h($x['event_text'])?></b><p><?=h($x['public_note'])?></p><small><?=h(date('M j, Y · g:i A',strtotime($x['created_at'])))?></small></div><?php endforeach;?></section>
</div>
<aside><form class="admin-panel" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><h2>Case action</h2><label>Status<select name="status"><?php foreach(['submitted','under_review','awaiting_response','resolved','closed','rejected'] as $s):?><option value="<?=$s?>" <?=$c['status']===$s?'selected':''?>><?=h(label($s))?></option><?php endforeach;?></select></label><label>Priority<select name="priority"><?php foreach(['low','normal','high','urgent'] as $p):?><option value="<?=$p?>" <?=$c['priority']===$p?'selected':''?>><?=h(ucfirst($p))?></option><?php endforeach;?></select></label><label>Reviewer response<textarea name="admin_response" rows="6"><?=h($c['admin_response'])?></textarea></label><label>Public timeline note<textarea name="public_note" rows="5" placeholder="Explain what changed for the claimant."></textarea></label><button class="btn orange full">Save case update</button></form></aside></div><?php require 'footer.php';?>