<?php
$title='Become a partner';require 'header.php';
$types=['agency'=>'Agency / consultancy','technology'=>'Technology / ISV','reseller'=>'Reseller / distributor','integrator'=>'Systems integrator'];
$type=$_GET['type']??'';
?>
<main class="apply-page"><aside><span class="kicker">PARTNER APPLICATION</span><h1>Let's build something useful together.</h1><p>This takes a few minutes. Tell us about your company, your market and the partnership motion you have in mind.</p><div class="aside-points"><span>✓ No program fee</span><span>✓ Human review</span><span>✓ Application tracking</span></div></aside>
<section class="application"><div class="form-head"><span class="kicker">STEP 1 OF 1</span><h2>Company &amp; partnership details</h2><p>We use this information to route your application to the right team.</p></div>
<form method="post" action="submit_application.php"><input type="hidden" name="csrf" value="<?=csrf()?>">
<div class="form-section"><h3>Company</h3><div class="grid2"><label>Company name *<input name="company_name" required placeholder="Acme Solutions"></label><label>Company website<input name="website" type="url" placeholder="https://acme.example"></label></div><div class="grid2"><label>Country / region<input name="country" placeholder="India"></label><label>Company size<select name="company_size"><option>1–10</option><option>11–50</option><option>51–200</option><option>201–1000</option><option>1000+</option></select></label></div></div>
<div class="form-section"><h3>Your contact</h3><div class="grid2"><label>Full name *<input name="contact_name" required placeholder="Jane Doe"></label><label>Work email *<input type="email" name="email" required placeholder="jane@company.com"></label></div><label>Phone<input name="phone" placeholder="+91 ..."></label></div>
<div class="form-section"><h3>Partnership</h3><div class="grid2"><label>Primary partner type *<select name="partner_type" required><?php foreach($types as $k=>$v):?><option value="<?=e($v)?>" <?=($type===$k?'selected':'')?>><?=e($v)?></option><?php endforeach;?></select></label><label>Primary region(s)<input name="regions" placeholder="India, Southeast Asia"></label></div><label>What do you offer? *<textarea name="services" required rows="4" placeholder="Describe your services, product or distribution capabilities."></textarea></label><label>Relevant experience<textarea name="experience" rows="4" placeholder="Customers, certifications, integrations, markets or delivery experience."></textarea></label><label>What would you like to achieve together? *<textarea name="goals" required rows="4" placeholder="Tell us about your ideal partnership and goals."></textarea></label></div>
<label class="terms"><input type="checkbox" required> I confirm the information is accurate and agree to be contacted about this application.</label><button class="btn primary full">Submit application <b>→</b></button></form></section></main><?php require 'footer.php';?>